jobs:
  build:
    name: JDK ${{ matrix.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: liberica
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      run: sudo apt-get install xvfb
    - continue-on-error: true
      run: sudo apt-get install gettext
    - continue-on-error: true
      name: Build with Maven
      run: xvfb-run mvn -Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true
        -Dprism.order=sw --batch-mode --update-snapshots verify
    strategy:
      matrix:
        java:
        - '21'
name: build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
